version: '3.8'
#sirve para manejar uno o varios contenedores que interactuen entre si
services:
  api-librero:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:3000    
    # para que el contenido que este en el contenedor se base en  una ubicación de nuestra máquina
    volumes:
    #lo que tenga en la carpeta src localmente sera lo mismo y todos los cambios se haran en el contenedor en la ubicación /app/src donde /app/ es el WORKDIR que definimos en el Dockerfile
      - ./src:/app/src
    depends_on:
    # este contenedor dependera de otro contenedor para que al momento de inicializarse de inicialice primero los detallados en esta lista
      - basededatos-mongo
    env_file: .env
    environment:
    # de mis varialbes seteadas previamente en el proyecto
      - MONGO_URL=mongodb://julissa:12345678@basededatos-mongo:27017
      - DBNAME=librero

  basededatos-mongo:
    image: mongo:latest
    ports:
      #externo:interno
      - 3000:27017
    environment:
      #son las variables que me da la imagen para poder acceder a esta bd desde afuera del contenedor
      #yml hay dos formas de declarar un arreglo
      #al poner guiones estamos indicando que va a ser un array y entonces deberiamos de colocar para los environments puro String sin la necesidad de colocar (llave-valor)
      # - MONGO_INITDB_ROOT_USERNAME=julissa
      # - MONGO_INITDB_ROOT_PASSWORD=12345678
      # - MONGO_INITDB_DATABASE=librero

      #en este formato las variables son representadas como JSON (llave-valor)
      # { MONGO_INITDB_ROOT_USERNAME: "eduardo", ... }

      MONGO_INITDB_ROOT_USERNAME: julissa
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: librero
